name = "LibCUDA"
uuid = "62f6ea4e-5fa0-47a8-a0b1-4c5959d5d2d3"
authors = ["Ciro B Rosa <ciro.rosa@alumni.usp.br>"]
version = "0.0.1"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"

[compat]
CUDA = "3.13 - 5.9"
julia = "1.8 - 1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
